### ISSUE TITLE
Styles loading slowness issue

### ISSUE THREAD

**Issue by mindbend0x** [FaisalAl-Tameemi/web3-login#8]
Currently, the styles (from AntDesign) take an extra second to load into the app which isn't ideal.

This cases the app contents to load into the page before the styles which doesn't look good. One possible solution here is to add splash / loading screen (image or  prior to displaying the contents of the app.

This issue has been discussed here: https://github.com/ant-design/ant-design/issues/40285

**Comment by monolithed** [comment]
@FaisalAl-Tameemi could you provide an example for Next@13 with `page` model?
